dist: xenial
sudo: false

language: node_js

node_js:
  - "10.12"

before_install:
  - sudo apt-get install libtool pkg-config build-essential autoconf automake
  - sudo wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add -
  - sudo apt-get install libzmq3-dev
  - sudo apt-get update
install:
  - npm install package.json

script:
  - npm test

after_success:
  - npm run report-coverage
