dist: xenial
sudo: false

language: node_js

node_js:
  - "10.12"

before_install:
  - sudo apt-get install -y pkg-config
install:
  - npm install package.json

script:
  - npm test

after_success:
  - npm run report-coverage
