language: node_js

node_js:
  - "10.16"

install:
  - npm install

script:
  - npm run test-tree
  - npm test

after_success:
  - npm run report-coverage

notifications:
  email:
    on_success: never
