dist: xenial
sudo: false

language: node_js

node_js:
  - "10.12"

before_install:
  - sudo apt-get install libtool pkg-config build-essential autoconf automake
  - sudo apt-get install libzmq-dev
  
install:
  - npm install package.json

script:
  - npm test

after_success:
  - npm run report-coverage
