language: node_js

node_js:
  - "10.16"

install:
  - npm install

script:
  - npm test
  - if [ ${TRAVIS_BRANCH} == "develop" ] || [ ${TRAVIS_BRANCH} == "master" ]; then echo $TRAVIS_BRANCH ; npm run test-tree; fi

after_success:
  - npm run report-coverage

notifications:
  email:
    on_success: never
