language: node_js

node_js:
  - "10.12"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends libzmq3-dev

install:
  - npm install

script:
  - npm test

after_success:
  - npm run report-coverage
