name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:10.15-alpine
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test-tree
      - run: npm test
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run report-coverage
